// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SongList.Web;

#nullable disable

namespace SongList.Web.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260119142927_Add_Holyrics_Sync")]
    partial class Add_Holyrics_Sync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SongList.Domain.HolyricsSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Formatting")
                        .HasColumnType("text");

                    b.Property<string>("HolyricsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lyrics")
                        .HasColumnType("text");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HolyricsId");

                    b.HasIndex("SongId", "HolyricsId")
                        .IsUnique();

                    b.ToTable("HolyricsSongs");
                });

            modelBuilder.Entity("SongList.Domain.HolyricsToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpiresIn")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HolyricsToken");
                });

            modelBuilder.Entity("SongList.Domain.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetailedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimpleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SongList.Domain.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("NoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasMaxLength(65536)
                        .HasColumnType("jsonb");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Song", (string)null);
                });

            modelBuilder.Entity("SongList.Domain.SongAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("S3Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("SongList.Domain.SongHistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HolyricsSongId")
                        .HasColumnType("integer");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HolyricsSongId");

                    b.HasIndex("SongId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("SongList.Domain.SongShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HolyricsSongId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsServiceFix")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsServiceModel")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsServiceTrain")
                        .HasColumnType("boolean");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("ShowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HolyricsSongId");

                    b.ToTable("SongShows");
                });

            modelBuilder.Entity("SongList.Domain.SongSlideHistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HolyricsSongId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ShowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlideNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("SongShowId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSlides")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HiddenAt");

                    b.HasIndex("HolyricsSongId");

                    b.HasIndex("ShowedAt");

                    b.HasIndex("SongShowId");

                    b.ToTable("SlideHistory");
                });

            modelBuilder.Entity("SongList.Domain.VerseHistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Book")
                        .HasColumnType("integer");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ShowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Verse")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShowedAt");

                    b.ToTable("VerseHistory");
                });

            modelBuilder.Entity("SongList.Domain.HolyricsSong", b =>
                {
                    b.HasOne("SongList.Domain.Song", "Song")
                        .WithMany("HolyricsSongs")
                        .HasForeignKey("SongId");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SongList.Domain.Song", b =>
                {
                    b.HasOne("SongList.Domain.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("SongList.Domain.SongAttachment", b =>
                {
                    b.HasOne("SongList.Domain.Song", "Song")
                        .WithMany("Attachments")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SongList.Domain.SongHistoryItem", b =>
                {
                    b.HasOne("SongList.Domain.HolyricsSong", "HolyricsSong")
                        .WithMany()
                        .HasForeignKey("HolyricsSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongList.Domain.Song", null)
                        .WithMany("History")
                        .HasForeignKey("SongId");

                    b.Navigation("HolyricsSong");
                });

            modelBuilder.Entity("SongList.Domain.SongShow", b =>
                {
                    b.HasOne("SongList.Domain.HolyricsSong", "HolyricsSong")
                        .WithMany()
                        .HasForeignKey("HolyricsSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolyricsSong");
                });

            modelBuilder.Entity("SongList.Domain.SongSlideHistoryItem", b =>
                {
                    b.HasOne("SongList.Domain.HolyricsSong", "HolyricsSong")
                        .WithMany()
                        .HasForeignKey("HolyricsSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongList.Domain.SongShow", null)
                        .WithMany("Slides")
                        .HasForeignKey("SongShowId");

                    b.Navigation("HolyricsSong");
                });

            modelBuilder.Entity("SongList.Domain.Song", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("History");

                    b.Navigation("HolyricsSongs");
                });

            modelBuilder.Entity("SongList.Domain.SongShow", b =>
                {
                    b.Navigation("Slides");
                });
#pragma warning restore 612, 618
        }
    }
}
