name: Build and deploy to remote server

on:
  push:
    branches: [ "master" ]
    
env:
  image_tag: ${{ secrets.DOCKERHUB_USERNAME }}/songlist:latest
  container_name: songlist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ env.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: deploy
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd songlist
            docker pull ${{ env.image_tag }}
            docker stop ${{ env.container_name }} || true && docker rm ${{ env.container_name }} || true
            docker run -d --name ${{ env.container_name }}  --env-file .env -p ${{ secrets.APP_PORT }}:80 ${{ env.image_tag }} 
